name: Build SwByeDPI
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Force Disable Code Signing
        run: |
          # Жестко удаляем требования к подписи из файла проекта
          sed -i '' 's/CODE_SIGNING_REQUIRED = YES/CODE_SIGNING_REQUIRED = NO/g' SwByeDPI.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGNING_ALLOWED = YES/CODE_SIGNING_ALLOWED = NO/g' SwByeDPI.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_ENTITLEMENTS = .*/CODE_SIGN_ENTITLEMENTS = "";/g' SwByeDPI.xcodeproj/project.pbxproj

      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies -project SwByeDPI.xcodeproj -scheme SwByeDPI

      - name: Build the App
        run: |
          xcodebuild clean archive \
            -project SwByeDPI.xcodeproj \
            -scheme SwByeDPI \
            -configuration Release \
            -sdk iphoneos \
            -archivePath SwByeDPI.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            ENTITLEMENTS_REQUIRED=NO

      - name: Package into IPA
        run: |
          mkdir -p Payload
          mv SwByeDPI.xcarchive/Products/Applications/*.app Payload/
          zip -r SwByeDPI.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SwByeDPI-IPA
          path: SwByeDPI.ipa
